runtime: java11
env: standard
entrypoint: java -Xmx64m -jar build/libs/word-learning.jar
runtime_config:
  jdk: openjdk11
instance_class: F2
automatic_scaling:
  max_instances: 1
env_variables:
  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_ID
  DATASOURCE_URL: $DATASOURCE_URL