name: Deploy prod
on: workflow_dispatch
jobs:
  deploy_backend:
    name: Deploy production backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
