name: Deploy prod
on:
  push:
    branches:
      - prod-frontend-deploy
jobs:
  deploy_frontend:
    name: Deploy production froented
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - uses: actions/checkout@v2
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
