name: Deploy prod
on:
  push:
    branches:
      - prod-frontend-deploy
jobs:
  deploy_backend:
    name: Deploy production backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
