on: workflow_dispatch
name: Deploy production
jobs:
  deploy_on_googles_app_engine:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Update access
        run: git update-index --chmod=+x gradlew
      - name: Run build with Gradle Wrapper
        run: gradlew build
      - uses: 73h/gae-app-yaml-replace-env-variables@v0.2
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
        with:
          app_yaml_path: "src/main/appengine/app.yaml"
      - uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_JSON }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: "Deploy"
        run: "gcloud app deploy build/libs/ --appyaml src/main/appengine/app.yaml --project wordlearningapplication --promote --version production"
